<?php



session_start();



if (!empty($_SESSION['admin'])) {
    require '../../config.php';
    if (!empty($_GET['kategori'])) {
        $nama = $_POST['kategori'];
        $tgl = date("j F Y, G:i");
        $data[] = $nama;
        $data[] = $tgl;
        $sql = 'INSERT INTO kategori (nama_kategori,tgl_input) VALUES(?,?)';
        $row = $config->prepare($sql);
        $row->execute($data);
        echo '<script>window.location="../../index.php?page=kategori&&success=tambah-data"</script>';
    }

    if (!empty($_GET['meja'])) {
        $nama = $_POST['meja'];
        $tgl = date("j F Y, G:i");
        $data[] = $nama;
        $data[] = $tgl;
        $sql = 'INSERT INTO meja (nama_meja,tgl_input) VALUES(?,?)';
        $row = $config->prepare($sql);
        $row->execute($data);
        echo '<script>window.location="../../index.php?page=meja&&success=tambah-data"</script>';
    }

    if (!empty($_GET['barang'])) {
        $id = $_POST['id'];
        $kategori = $_POST['kategori'];
        $nama = $_POST['nama'];
        $jual = $_POST['jual'];
        $satuan = $_POST['satuan'];
        $stok = $_POST['stok'];
        $tgl = $_POST['tgl'];

        $data[] = $id;
        $data[] = $kategori;
        $data[] = $nama;
        $data[] = $jual;
        $data[] = $satuan;
        $data[] = $stok;
        $data[] = $tgl;
        $sql = 'INSERT INTO barang (id_barang,id_kategori,nama_barang,harga_jual,satuan_barang,stok,tgl_input) 
			    VALUES (?,?,?,?,?,?,?) ';
        $row = $config->prepare($sql);
        $row->execute($data);
        echo '<script>window.location="../../index.php?page=barang&success=tambah-data"</script>';
    }

    if (!empty($_GET['userList'])) {

        error_reporting(E_ALL);
        ini_set('display_errors', 1);
        $user = $_POST['user'];
        $pass = $_POST['pass'];
        $role = $_POST['role'];
        $nm_member = $_POST['nm_member'];
        $alamat_member = $_POST['alamat_member'];
        $telepon = $_POST['telepon'];
        $email = $_POST['email'];
        $NIK = $_POST['NIK'];

        $gambartemp = $_FILES['gambar']['tmp_name'];

        $xx = rand(10000000, 99999999);
        // Get the image file and move it to the images folder
        $gambarPath = $_SERVER['DOCUMENT_ROOT'] . "/UKK-WEB/CafeCabs/assets/img/user/" . $xx . "_" . basename($_FILES['gambar']['name']);


        move_uploaded_file($gambartemp, $gambarPath);
        // Insert data into the member table
        $sql1 = 'INSERT INTO member (nm_member, alamat_member, telepon, email, NIK, gambar) VALUES (?, ?, ?, ?, ?, ?)';
        $row1 = $config->prepare($sql1);
        $row1->execute([$nm_member, $alamat_member, $telepon, $email, $NIK, $xx . "_" . basename($_FILES['gambar']['name'])]);

        // Get the id_member generated by the previous insert
        $id_member = $config->lastInsertId();

        // Insert data into the login table
        $sql2 = 'INSERT INTO login (user, pass, role, id_member) VALUES (?, ?, ?, ?)';
        $row2 = $config->prepare($sql2);
        $row2->execute([$user, md5($pass), $role, $id_member]);

        echo '<script>window.location="../../index.php?page=userList&success=tambah-data"</script>';
    }

    if (!empty($_GET['jual'])) {
        $id = $_GET['id'];

        // get tabel barang id_barang
        $sql = 'SELECT * FROM barang WHERE id_barang = ?';
        $row = $config->prepare($sql);
        $row->execute(array($id));
        $hsl = $row->fetch();

        if ($hsl['stok'] > 0) {
            $kasir =  $_GET['id_kasir'];
            $jumlah = 1;
            $total = $hsl['harga_jual'];
            $tgl = date("j F Y, G:i");

            $data1[] = $id;
            $data1[] = $kasir;
            $data1[] = $jumlah;
            $data1[] = $total;
            $data1[] = $tgl;

            $sql1 = 'INSERT INTO penjualan (id_barang,id_member,jumlah,total,tanggal_input) VALUES (?,?,?,?,?)';
            $row1 = $config->prepare($sql1);
            $row1->execute($data1);

            echo '<script>window.location="../../index.php?page=jual&success=tambah-data"</script>';
        } else {
            echo '<script>alert("Stok Barang Anda Telah Habis !");
					window.location="../../index.php?page=jual#keranjang"</script>';
        }
    }
}
